#!/bin/sh

set -ex
[ "$1" == "--i-run-this-in-container" ]

ARCH=arm64
dpkg --add-architecture $ARCH

apt-get update
apt-get install binutils-multiarch-dev \
	g++-aarch64-linux-gnu gawk gcc-aarch64-linux-gnu git gzip locales make \
	multiarch-support pkg-config python python-docutils yasm libc6-dev \
	libc6-dev-$ARCH-cross libc6-dev:$ARCH

prepare() {
	if [ -d $1 ]; then
		cd $1 && git reset --hard && git pull
	else
		git clone -b "$3" "$2" $1
	fi
	cp -a packaging/$1 $1/debian
	cd $1 && patch -p1 < "../patches/$1.diff"
	apt-get build-dep -y $1
}

# git clone https://github.com/ptitSeb/gl4es.git
prepare FFmpeg https://github.com/LongChair/FFmpeg.git rockchip
prepare mpv https://github.com/LongChair/mpv.git rockchip

build() {
	cd $1 && dpkg-buildpackage -b -us -uc -a arm64
}

build FFmpeg
build mpv
