#!/bin/sh

set -ex
[ "$1" == "--i-run-this-in-container" ]

ARCH=arm64
dpkg --add-architecture $ARCH

apt-get update
apt-get install binutils-multiarch-dev \
	g++-aarch64-linux-gnu gawk gcc-aarch64-linux-gnu git gzip locales make \
	multiarch-support pkg-config python python-docutils yasm libc6-dev \
	libc6-dev-$ARCH-cross libc6-dev:$ARCH

# git clone https://github.com/ptitSeb/gl4es.git
git clone -b rockchip https://github.com/LongChair/FFmpeg.git 
git clone -b rockchip https://github.com/LongChair/mpv.git

prepare() {
	cp -a packaging/$1 $1/debian
	cd $1 && patch -p1 < "../patches/$1"
	apt-get build-dep -y $1
}

prepare FFmpeg
prepare mpv

build() {
	cd $1 && dpkg-buildpackage -b -us -uc -a arm64
}

build FFmpeg
build mpv
